### ISSUE TITLE
SSL write failure when redeploying haproxy container on Tutum

### ISSUE THREAD

**Issue by markfsuk** [tutumcloud/haproxy#103]
This has started fairly recently, when I try redeploy a container built on tutum/haproxy:latest (I've tried previous tags also) I am getting:

Unexpected error executing docker command create_container: [('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]

I am using SSL termination via the DEFAULT_SSL_CERT environment variable in the haproxy tutum stack.

Docker version is: 1.8.3 build f4bf5c7 if that's of any help.

**Comment by tifayuki** [comment]
Where does the log come from? 
Looks like it is from docker daemon and it fails to create container because of an SSL issue.

**Comment by markfsuk** [comment]
I see this message on the Tutum timeline (and as a modal popup) whenever I try restarting the haproxy stack or service.

**Comment by markfsuk** [comment]
I believe this was down to some oddness with the Tutum agent install on my node, and not related specifically to Haproxy, so closing this one.

**Comment by kitwalker12** [comment]
@markfsuk Could you elaborate more on what caused this issue for you. I'm facing the same problem after I linked haproxy to 2 services

**Comment by markfsuk** [comment]
@kitwalker12 The only way I could solve the issue in the end after many messages between myself and Tutum support was to remove all containers and install tutum-agent on my node (i.e. turn it all off and on again). Tutum suggested it could have been due to the certificate used in /etc/tutum/agent/ was invalid for some reason and thus tutum could not contact the docker daemon properly. After removing ca.pem, cert.pem, key.pem and restarting the agent (which recreates the certs) I still had the issue, but after removing all containers and redoing the "bring your own node" steps on the Tutum site the problem went away.

Oddly enough now, I still see the issue *occasionally* but terminating and redeploying the container and also haproxy gets rid of it, I still feel there is a bug somewhere causing it but I failed to identify the precise cause personally. One thing I did note is I see in the /var/log/tutum/docker.log "http: TLS handshake error from 54.175.142.88:59893: EOF" (the IPs vary slightly and are Tutum's) when the issue occurs, though I'm still seeing this sporadically now so it may be unrelated.

**Comment by arzynik** [comment]
thanks @markfsuk

i recently had this issue when i was changing certs around. this worked for me.

```sh
service tutum-agent stop
rm /etc/tutum/agent/ca.pem
rm /etc/tutum/agent/cert.pem
rm /etc/tutum/agent/key.pem 
service tutum-agent start
```

**Comment by johanndt** [comment]
Just saved my life @arzynik. Had the exact same problem just randomly appear (after we've been using the exact same setup for 6 months or more). Your solution worked perfectly.

**Comment by markfsuk** [comment]
I can still replicate this issue unfortunately, even after removing the certs and restarting - which was one of the things Tutum support suggested. It happens for me now consistently when I have more than 10 services linked in the tutumcloud/haproxy stack.

**Comment by pilwon** [comment]
@tifayuki @fermayo I also keep getting this frustrating error messages...

**Comment by johanndt** [comment]
Okay, this just spontaneously happened again. I was bouncing one of my web workers, and haproxy didn't want to link to it. And when I tried to redeploy haproxy, I got the SSL issue again. :-(

Doing the cert deletion and tutum-agent restart did fix it again, but that restarts the whole stack again - which caused several minutes of downtime.

**Comment by franky-continu** [comment]
+1 could not resolve it

**Comment by Levino** [comment]
Same here. Please tutum team, get this fixed. Downtime of the load balancers is really worst case...

**Comment by fermayo** [comment]
This seems to be a urllib3 issue: https://github.com/shazow/urllib3/pull/719
We'll be cherry picking that fix and put it on our production environment ASAP. Sorry for the trouble

**Comment by markfsuk** [comment]
That's great news, thanks @fermayo.

**Comment by tifayuki** [comment]
The fix of urllib3 issue has been pushed online. Should not see the error any more.

**Comment by franky-continu** [comment]
sweet!
Franky Diaz-Trepat
Full Stack Engineer
+1 (720) 295-0592 / 401-1276
skype: franky.diaz.trepat
franky@continu.co

**Comment by markfsuk** [comment]
Excellent news, I'll give this a try today.

**Comment by Levino** [comment]
Good stuff.

**Comment by markfsuk** [comment]
It looks like this is working as expected for us now so I'm closing this issue. Thanks for sorting it.

**Comment by johanndt** [comment]
Thanks everyone. @markfsuk and @tifayuki - I can see commit in urllib3, but it doesn't seem to be on PyPi yet. What exactly is needed to do the fix?

Just redeploy the official haproxy image? Or redeploy tutum-agent? (I'm on BYON).

Thanks.

**Comment by tifayuki** [comment]
@johanndt 

We patched the fix directly to the urllib3 used on our server side. The error has nothing to do with this image. You don't have to do anything.
