### ISSUE TITLE
SSL_CERT + FORCE_SSL + VIRTUAL_HOST doesnt work

### ISSUE THREAD

**Issue by sandcastle** [tutumcloud/haproxy#112]
I'm not sure if I'm missing something, but I cannot seem to get FORCE_SSL=yes to work when combined with SSL_CERT=blah and VIRTUAL_HOST. Should this work?

The examples do not show the above combo:

```
docker run -d -e FORCE_SSL=yes -e SSL_CERT="YOUR_CERT_TEXT" --name webapp tutum/hello-world
docker run -d --link webapp:webapp -p 443:443 tutum/haproxy
```

**Comment by modius** [comment]
Are you including the scheme in VIRTUAL_HOST?

For example,
```
    - FORCE_SSL=yes
    - VIRTUAL_HOST=https://www.daemon.com.au
    - SSL_CERT="-----BEGIN RSA PRIVATE KEY-----
```

**Comment by sandcastle** [comment]
Yes, I have specified the scheme in the VIRTUAL_HOST. According to the readme this needs to be set.

```
SSL termination is enabled when:

at least one SSL certificate is set, and
either VIRTUAL_HOST is not set, or it is set with "https" as the scheme.
```

**Comment by BastienSemene** [comment]
@sandcastle it works for me on `latest` (not tested previous versions).
I have 2 services load-balanced which have `VIRTUAL_HOST`configured on each, and only one of them has `SSL_CERT` and `FORCE_SSL`. Both services listen on port `80`and `443`.

**Comment by tifayuki** [comment]
To make it work, you need:
- publish both port `80` and `443` of the tutum/haproxy container
- set both http and https url in VIRTUAL_HOST in the underlying service, e.g. `VIRTUAL_HOST='https://example.org, http://example.org'`
- set `FORECE_SSL=yes` in the underlying service
- set `SSL_CERT=<your_cert_key_pem>` in the underlying service

**Comment by sandcastle** [comment]
@tifayuki - thank you! :tada:

**Comment by danawoodman** [comment]
Not that I did not need to set the `SSL_CERT` on every underlying service. Setting in the `tutum/haproxy` service was sufficient.
