### ISSUE TITLE
Is DEFAULT_SSL_CERT required?

### ISSUE THREAD

**Issue by modius** [tutumcloud/haproxy#113]
If I set up HAPROXY with a default SSL all appears to work as expected.

If I set up a service with SSL_CERT without nominating a DEFAULT_SSL_CERT then I get the following error:
```
parsing [/haproxy.cfg:36] : 'bind :443' : unable to load SSL private key from PEM file '/certs/cert0.pem'.
Error(s) found in configuration file : /haproxy.cfg
Proxy 'port_443': no SSL certificate specified for bind ':443' at [/haproxy.cfg:36] (use 'crt').
Fatal errors found in configuration.
```

Does this mean DEFAULT_SSL_CERT is required.. or is something else wrong?

**Comment by tifayuki** [comment]
`    envvar_default_ssl_cert = os.getenv("DEFAULT_SSL_CERT") or os.getenv("SSL_CERT")`
In tutum/haproxy container, DEFAULT_SSL_CERT and SSL_CERT are the same.

The problem of your issue is that there is no private key your pem file.
