### ISSUE TITLE
Ordering of backend rules

### ISSUE THREAD

**Issue by joonathan** [tutumcloud/haproxy#116]
Right now rules are passed through sorted() but this could cause issues for rules that need to be ordering aware, for example:

acl has_trailing_slash path_end  /
reqrep ^(.*?)[\/]+$ \1
redirect prefix / code 301 if has_trailing_slash

For this example the final order would have redirect clause before reqrep and this would cause a redirection loop as the url would not have been modified beforehand.

**Comment by tifayuki** [comment]
True, I have removed the sorted():https://github.com/tutumcloud/haproxy/commit/40833082ab4a7cf77a52616cb7183bd5f3300994

Thanks for pointing it out
