### ISSUE TITLE
Allow frontend append

### ISSUE THREAD

**Issue by swleighton** [tutumcloud/haproxy#117]
Hi,

I'm trying to redirect requests from https://www.mysite.com to always go to https://mysite.com

Reading the haproxy docs I need to add the following to the frontend config:
redirect prefix https://www.site.com code 301 if { hdr(host) -i domain.com }

however there seems no way to pass this through via environment variables 

Am i missing something or would you like this feature including - I'm quite happy to write the code and add it all a pull request.  

Thanks,
Simon

**Comment by tifayuki** [comment]
There is some "EXTRA_SETTINGS" env var in the README, where you can inject some clauses if needed

**Comment by tifayuki** [comment]
http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4.2-redirect%20prefix

The redirect prefix instruction is available in backend section haproxy configuration. Thus, you can specify it using "EXTRA_SETTINGS" in the underlying services.

**Comment by swleighton** [comment]
Hi tifayuki,

Thanks very much for the answer! 

Simon
