### ISSUE TITLE
Wildcard virtual host not working (catch all)

### ISSUE THREAD

**Issue by Dids** [tutumcloud/haproxy#123]
So far HAProxy seems to be working fine, and I can get a specific domain working fine, when using ```VIRTUAL_HOST=http://my-domain.com``` with ```VIRTUAL_HOST_WEIGHT=2```.

I'm also trying to catch all other matches with a ```VIRTUAL_HOST=*``` and ```VIRTUAL_HOST_WEIGHT=1```.

Unfortunately, using * as the virtual host doesn't seem to catch any domains, and just results in a 503 status code. I've also tried with ```VIRTUAL_HOST=http://*```, but with the exact same results.

Any ideas/tips would be greatly appreciated!

**Comment by Dids** [comment]
Something weird is definitely going on, because I can clearly see the environment variables for both of these services, but HAProxy is not taking the "catch all" virtual host in to consideration at all, as you can see here:
```
haproxy-1 | 2015-12-06T17:31:18.123635741Z frontend port_80
haproxy-1 | 2015-12-06T17:31:18.123640616Z   bind :80 
haproxy-1 | 2015-12-06T17:31:18.123644888Z   acl is_websocket hdr(Upgrade) -i WebSocket
haproxy-1 | 2015-12-06T17:31:18.123649191Z   acl host_rule_1 hdr(host) -i app2.domain.com
haproxy-1 | 2015-12-06T17:31:18.123653456Z   acl host_rule_1_port hdr(host) -i app2.domain.com:80
haproxy-1 | 2015-12-06T17:31:18.123657752Z   use_backend SERVICE_APP2 if host_rule_1 or host_rule_1_port
haproxy-1 | 2015-12-06T17:31:18.123662057Z backend SERVICE_APP1
haproxy-1 | 2015-12-06T17:31:18.123666322Z   appsession JSESSIONID len 52 timeout 3h
haproxy-1 | 2015-12-06T17:31:18.123670443Z   balance source
haproxy-1 | 2015-12-06T17:31:18.123674592Z   cookie SRV insert indirect nocache
haproxy-1 | 2015-12-06T17:31:18.123678868Z   option httpchk HEAD /health HTTP/1.0
haproxy-1 | 2015-12-06T17:31:18.123683034Z   server NGINX_1 10.7.0.5:80 cookie NGINX_1 check
haproxy-1 | 2015-12-06T17:31:18.123687184Z backend SERVICE_APP2
haproxy-1 | 2015-12-06T17:31:18.123691315Z   option httpchk HEAD /health HTTP/1.0
haproxy-1 | 2015-12-06T17:31:18.123695538Z   server APP2_1 10.7.0.3:5000 check
```

**Comment by Dids** [comment]
Hmm, I added ```*/, */*``` to ```VIRTUAL_HOST``` and it seems to be now catching all domains.

Is this a regex bug, or done on purpose?

**Comment by tifayuki** [comment]
It is a bug.
When setting `*`, the `path` returned by urlparse is empty, which makes both host_rule and path_rule ignore the VIRUTAL_HOST setting.

I will fix it soon.

Thank you for reporting this :)
