### ISSUE TITLE
HAProxy 504 with configuration that used to work

### ISSUE THREAD

**Issue by awsmsrc** [tutumcloud/haproxy#133]
Hey gang,

I have been really enjoying using tutum.

I have tried through the slack community, twitter and the support email to get a response as I didn't want to spam the github account with issues.

For some reason about a week ago haproxy started timing out.
There is nothing obvious that has changed in my configuration and there is nothing obvious in the logs of haproxy (forwarded to papertrail)

My app is accessible by using the service endpoint provided by tutum

Any help appreciated

**Comment by Levino** [comment]
Are there no logs you can share? What is the backend? HTTP servers? What domain is your app running on?

**Comment by tifayuki** [comment]
504 Gateway timeout returned in Haproxy means that haproxy forwards the request to your application, but it cannot receive the response in time. It could be a network issue, but mostly there could be a bug on the user's application side.

If nothing is changed, I mean both on your application and the haproxy container, it could be the issue/bug of haproxy program itself. Can you try to redeploy the haproxy container to see if it is fixed.

**Comment by awsmsrc** [comment]
hey sorry guys as i said i didn't want to spam here.
Ive figured it out and, predictably, it was my fault.

The timeout in HAProxy was a lot lower then the timeout in my db connection code ;)

Apologies, loving tutum so far
