### ISSUE TITLE
Configuration file missing error in Tutum

### ISSUE THREAD

**Issue by varuna82** [tutumcloud/haproxy#150]
I have tried to configure and deploy latest version of HAProxy service using Tutum. However, HAProxy service "stops" automatically after a while with following error message.
```
haproxy-25304adf-1 | 2016-01-21T12:01:58.623733330Z [ALERT] 020/120158 (1) : Could not open configuration file /usr/local/etc/haproxy/haproxy.cfg : No such file or directory
```

**Comment by tifayuki** [comment]
Hello,
How did you deploy the haproxy, can you paste the stackfile and paste the full logs?

**Comment by varuna82** [comment]
Thanks for the quick reply.

I haven't used any stack files and configuration file missing is the only thing I had in log file. I've used the instructions in following link to create an HAProxy service.
http://docker.grandvillericks.com/haproxy-docker-tutum/

I am pretty new to Tutum, Docker and HAProxy. I might be missing something here.
Run command used by the service is:
```
Run command haproxy -f /usr/local/etc/haproxy/haproxy.cfg (Using value defined on image)
```
It might have something to do with this.

**Comment by tifayuki** [comment]
You should not change the RUN command if you are using `tutum/haporxy`.

**Comment by varuna82** [comment]
Run Command seems to be mandatory when I use Tutum's Web UI.

**Comment by varuna82** [comment]
My mistake. I have been using Docker's HAProxy all along. I'll try with Tutum's HAProxy now.

**Comment by varuna82** [comment]
Using Tutum's HAProxy fixed the problem. Thanks for the help.
