### ISSUE TITLE
Service link alias must match container name now?

### ISSUE THREAD

**Issue by miracle2k** [tutumcloud/haproxy#151]
I redeployed on Tutum with the latest version of haproxy, and all virtual hosts broke - all linked services were served from the default frontend.

I fixed this my following the config instructions to a t and making sure the link alias has the same name as the service linked to. Before, I might have had a service called  "app", but called the haproxy link "mysite-app".

Something changed that this repo no now longer recognizes these links as separate frontends (despite the services specifying VIRTUAL_HOST etc).

Was this functionality lost on purpose?

I should say that this is related to something that bothers me in the Tutum UI, as well. It's not uncommon for me to call one service within my stack "app", another one "db", and obviously these names clash easily with other stacks.

I assume it would not be possible for me to use tutumcloud/haproxy with two separate backends, both of which are called "app" - not if I am not able to rename the alias. No?

**Comment by tifayuki** [comment]
Hello @miracle2k 

Thank you for letting us know this issue. I made a mistake of match the container names. Sorry for the inconvenience.

The fix is in `tutum/haproxy:0.2.4.1`. Please check out if it solves your problem.

Thank you
