### ISSUE TITLE
did the syntax change with version 2 or what?

### ISSUE THREAD

**Issue by kklepper** [tutumcloud/haproxy#158]
docker-compose.yml version 1

    web:
      expose:
        - "5000"
      image: tutum/hello-world:latest
    
    lb:
      image: tutum/haproxy
      links:
        - web
      ports:
        - "8081:80"
        - "1936:1936"
      expose:
        - 80
      environment:
        - BACKEND_PORT=5000
        - BALANCE=roundrobin
test

    sudo docker-compose up -d 
    sudo docker-compose scale web=5 
    sudo docker-compose up --force-recreate -d

works as expected

docker-compose.yml version 2, same as before, except services added

    version: '2'
    
    services:
    
      web:
        expose:
          - "5000"
        image: tutum/hello-world:latest
    
      lb:
        image: tutum/haproxy
        links:
          - web
        ports:
          - "8081:80"
          - "1936:1936"
        expose:
          - 80
        environment:
          - BACKEND_PORT=5000
          - BALANCE=roundrobin

test

    sudo docker-compose up -d 
    sudo docker-compose scale web=5 
    sudo docker-compose up --force-recreate -d

timeout

**Comment by tifayuki** [comment]
compose v2 manages links differently from v1.
see : #157

**Comment by kklepper** [comment]
@tifayuki Sorry, this is no answer. Does the new version work or not, and if so, which part of the syntax is to change how?

**Comment by fermayo** [comment]
@kklepper we are working to make `dockercloud/haproxy` "compatible with Compose v2", which is in reality making it work with the new links introduced in Docker 1.10. This image is not tied to any Compose format.

**Comment by kklepper** [comment]
@fermayo Oh, I see, this means it does not work yet with v2 - if I'm wrong please correct me. Thank you.

**Comment by fermayo** [comment]
Correct. We're working on that as we speak.
