### ISSUE TITLE
FORCE_SSL with HTTPS termination not working

### ISSUE THREAD

**Issue by smiffy6969** [tutumcloud/haproxy#162]
Hiya,

Managed to get SSL cert working on ha proxy... I have set snakeoil cert and key in my application environment variable along with FORCE_SSL set to yes and VIRTUAL_HOST set to https://.......

The problem I am having is https works fine when terminiation starts with https, and all is well, but if I go to http it does not redirect to https.

Now if I set http termination on the VIRTUAL_HOST variable, and have FORCE_SSL set to yes, I get redirect on https fine, but https does not resolve... I get site cannot be reached.

Now the readme says you needd to have termination set to https and cert set to get force_ssl to work, I can only seem to get force_ssl to work when anything BUT https is set in termination on VIRTUAL_HOST variable. But I can only get https to resolve and connect when i sepcifically set it on VIRTUAL HOST.

So the issue is I can only get the force ssl to work when I set anything but https as a prefix to VIRTUAL_HOST, but doing so breaks the site and stops connection (although I can get https to work by setting this as the prefix, which breaks redirect).

What am I doig wrong here, I have tried making sure I am running latest compose ^1.6 and engine, this is driving me nuts!

cheers

Paul

**Comment by smiffy6969** [comment]
Ok I have just checked stats on ha proxy... setting anything but https as prefix for virtual_host stops the 443 port coming up, so I have to have https as stated, to get 443 port up, but I get no force to https from http when setting prefix to https....... ahhhhhhhhh :( been at this days and days )

**Comment by tifayuki** [comment]
You have to set `FORCE_SSL=yes` and `VIRTUAL_HOST="http://your.domain, https://your.domain"`

**Comment by smiffy6969** [comment]
holly crap... the one thing I did not try, what a dumb ass.... thank you kind sir, you win a cigar :) I know you can do wild cards, set mutliple addresses but I didnt think for one second tha I would have to do http and s together... such a long long week already. cant thank you enough.
