### ISSUE TITLE
Linked service SSL_CERT change (with a redeploy) does not get picked up automatically

### ISSUE THREAD

**Issue by sunshineo** [tutumcloud/haproxy#169]
After change the SSL_CERT of a linked service then redeployed that linked service, haproxy seems to still serve the old cert. Even though on the tutum configuration -> environment variable page it shows the new cert as the environment variable for the haproxy service, I have to redeploy the haproxy for it to take effect.

**Comment by sunshineo** [comment]
As a matter of fact, nothing works automatically for me including 'VIRTUAL_HOST' changes.

**Comment by sunshineo** [comment]
This is really annoying even though https://github.com/tutumcloud/haproxy#settings-in-linked-application-services says it should work automatically.
Are we encouraged to move to the official HAPROXY docker image?
Does that work with linked services in cloud.docker.com?

**Comment by samuelgiles** [comment]
This repo has moved to the Docker organisation since Tutum became DockerCloud: https://github.com/docker/dockercloud-haproxy

**Comment by sunshineo** [comment]
Thank you!
