### ISSUE TITLE
Possible to have other common LB features?

### ISSUE THREAD

**Issue by ashish235** [tutumcloud/haproxy#36]
Is it possible to have other configurations like:
1. Service type: Layer5 TCP/Layer7 HTTP
2. X-Forwarding or X-header or IP impersonating
3. Sticky bit.

These configurations can make tutum real handy. 

Thanks.

**Comment by motin** [comment]
1. Yes, MODE tcp = layer 5, MODE http = layer 7
2. You should be able to use "option forwardfor" by using the OPTION env var
3. There seems to be an undocumented env var for sticky sessions: https://github.com/tutumcloud/tutum-docker-clusterproxy/blob/master/haproxy.py#L159

**Comment by ashish235** [comment]
Great! Thanks, for the reply. Will try out these options.

**Comment by tifayuki** [comment]
@motin Thank you for the reply. I will add the missing environment variable to the README soon.

**Comment by Taik** [comment]
Just adding on to this; Would be really nice to have some documentation for enabling websockets as a use case as well.

**Comment by Joostvanderlaan** [comment]
@Taik I can confirm Websockets work out of the box (tested with Meteor)
Sticky sessions is another story... They are not enabled by default. So for example when you disable Websockets in Meteor by setting the ENV var DISABLE_WEBSOCKETS=1 Meteor doesn't work. But I'll look into that undocumented ENV var @motin is talking about tomorrow.

**Comment by Joostvanderlaan** [comment]
From: http://blog.haproxy.com/2013/04/22/client-ip-persistence-or-source-ip-hash-load-balancing/
BALANCE=source should work I guess...

**Comment by Joostvanderlaan** [comment]
I can confirm BALANCE=source will do the trick!

**Comment by tifayuki** [comment]
at tcp level, we can use `BALANCE=source` for affinity.
at http level, we can use either `appsession` or `cookie`(or balance=source, not recommended).

`appsession` is documented in staging and I will add the `cookie` method ASAP.
Notice: current version on master will be deprecated soon.

**Comment by tifayuki** [comment]
https://github.com/tutumcloud/haproxy/commit/30c6694a9ae42f8664ed07946165d9e09590785d
