### ISSUE TITLE
hdr_end not working as expected

### ISSUE THREAD

**Issue by inkrement** [tutumcloud/haproxy#42]
I want to use wildcards with some sort of overwrite-functionality:

> *.example.com -> service1 
> web.example.com -> service2

is this somehow possible?

if I set `VIRTUAL_HOST` to `service1=example.com, service2=web.example.com` it's not working like expected because all requests are redirected to service1.

How can I achieve the given setup?

**Comment by tifayuki** [comment]
When using `hdr_end`, `web.example.com` will falls in to the rule of  `hdr_end(example.com)`. This option is for those who need different domains not overwrite something in the same domain.

I need look into if it possible to do the `overwrite-functionality`.

**Comment by tifayuki** [comment]
I have pushed a new version on staging: `tutum/haproxy:staging`. it supports multi-ssl certs, virtual host with different ports and virtual path. 

hdr_beg/end will be removed. you can not specify virtual host using `*.example.com` now.

**Comment by tifayuki** [comment]
There is no hdr_end environment any more.
This issue will be solve in https://github.com/tutumcloud/haproxy/issues/68
