### ISSUE TITLE
haproxy SSL termination for multiple certificates

### ISSUE THREAD

**Issue by cvwj** [tutumcloud/haproxy#45]
Currently the haproxy image handles 1 SSL certificate. How about supporting multiple certificates? In our case, we have no less than 4, and it would be beautiful if the loadbalancer of the setup could handle them all.
Right now we have to install an nginx for handling multiple ssl certificate termination and forward to the loadbalancer. 
Looking into the Dockerfile of tutum/haproxy, it seems possible, even though I myself is not enough into python and haproxy to supply a patch.

**Comment by tifayuki** [comment]
I would suggest to add an environment HAPROXY_SSL_CERT to your service/container. When it is linked to haproxy, haproxy will read the environment variable and set the certificate on different virtual host.

I will implement it soon. Any suggestion?

**Comment by cvwj** [comment]
I think it should probably be set directly on the load balancer relieving all other containers of the concern of SSL termination. They will be within a protected zone, guarded by the load balancer and need only think about ordinary http. 

Could you introduce a pattern of SSL environment variables like:
SSL_CERT_<VIRTUAL_HOST>

If the certificate is a wild card certificate, then the <VIRTUAL_HOST> part could be prefixed with a * like:
*.example.com, thereby terminating for any request that ends with 'example.com'.

**Comment by johnjelinek** [comment]
@tifayuki: any updates on this implementation?

**Comment by tifayuki** [comment]
I have pushed a new version on staging: `tutum/haproxy:staging`. it supports multi-ssl certs, virtual host with different ports and virtual path

**Comment by tifayuki** [comment]
https://github.com/tutumcloud/haproxy/commit/70c371a4a4b869c10af5aa4c33c0ea372450bb8a
