### ISSUE TITLE
Ability to specify several frontend ports

### ISSUE THREAD

**Issue by develar** [tutumcloud/haproxy#48]
I need to configure listening on 80 and 443 ports, but currently I can set only one port (FRONTEND_PORT).

I don't want to configure haproxy SSL (my nginx has it and I don't want to maintain yet another configuration) — I set mode to tcp (I don't use virtual hosts or other http-related functionality).

**Comment by ehacke** [comment]
+1 It seems like right now I'd have to have a single haproxy service for 80, and another for 443

**Comment by tifayuki** [comment]
I have pushed a new version on staging: `tutum/haproxy:staging`. it supports multi-ssl certs, virtual host with different ports and virtual path

**Comment by tifayuki** [comment]
https://github.com/tutumcloud/haproxy/commit/70c371a4a4b869c10af5aa4c33c0ea372450bb8a
