### ISSUE TITLE
Add support for Virtual Path

### ISSUE THREAD

**Issue by munjalpatel** [tutumcloud/haproxy#50]
Hello,

Only having virtual hosts are not sufficient for certain micro-service based architecture.

One example is that we have different micro-services for reporting, data warehouse, etc.

Because wildcard SSL only works for the first-level subdomains, we would like to use `manage.domain.com/reporting` URL scheme instead of `reporting.manage.domain.com`

Here, `manage.domain.com/reporting` and `manage.domain.com/data-warehouse` should be two different micro-services running in two different containers.

**Comment by Tebro** [comment]
+1

**Comment by cvwj** [comment]
+1 - this would make it easier to handle CORS issues.

**Comment by tifayuki** [comment]
I was thinking to define VIRTUAL_HOST in the format of `http://user:pass@www.tutum.co:80/test` and I will parse the string and extract `test` as the virtual pass.

Any suggestion?

**Comment by develar** [comment]
Do you mean introducing new env var or reuse existing VIRTUAL_HOST? I like your idea — you can just take in account path in the specified HOST. Instead of introducing another env var.

Currently, we can specify several virtual hosts using comma-separated list: VIRTUAL_HOST="www.webapp1.com, www.webapp1.org" (linked container environment variables).
There is theoretical use case: if you want to use the same path for all specified domains, env var like VIRTUAL_PATH could be useful to avoid duplication. But it adds complexity.

**Comment by tifayuki** [comment]
A new environment variable, the next update could be a breaking change. At lease I will remove `VIRTUAL_HOST` from the haproxy container. I will give the current stable version a tag (tutum/haproxy:1.0) before any breaking changes.

Basically, what specified in haproxy container will go to default and global section. All the service/container specific settings should be set in the linked containers using`HAPROXY_XXXXX`, such as `HAPROXY_VIRTUAL_HOST`, `HAPROXY_SSL_CERT`, `HAPROXY_BASIC_AUTH`, etc.

`HAPROXY_VIRTUAL_HOST` can be, of course, a list of domains. I am not very sure what is the best way to combine `hdr`, `hdr_beg`,`hdr_end` with domains, and `path`, `path_beg`, `path_end` with virtual path.

**Comment by develar** [comment]
> what is the best way to combine hdr, hdr_beg,hdr_end with domains

Please get rid of them. Consider to use wildcards ("*") — https://github.com/jwilder/nginx-proxy#wildcard-hosts

**Comment by johnstontrav** [comment]
+1 any news on this?  CORS would be a big bonus!

**Comment by johnstontrav** [comment]
Hi @tifayuki, are there any plans on implementing the feature that @munjalpatel stated in first post?

>Because wildcard SSL only works for the first-level subdomains, we would like to use manage.domain.com/reporting URL scheme instead of reporting.manage.domain.com

>Here, manage.domain.com/reporting and manage.domain.com/data-warehouse should be two different micro-services running in two different containers.

**Comment by tifayuki** [comment]
I have pushed a new version on staging: `tutum/haproxy:staging`. it supports multi-ssl certs, virtual host with different ports and virtual path

**Comment by tifayuki** [comment]
https://github.com/tutumcloud/haproxy/commit/70c371a4a4b869c10af5aa4c33c0ea372450bb8a
