### ISSUE TITLE
Use safe default ciphers for SSL_BIND_CIPHERS

### ISSUE THREAD

**Issue by advancingu** [tutumcloud/haproxy#51]
When running with the default configuration, the score assigned by [SSL Labs' Quality test](https://www.ssllabs.com/ssltest) for a site served by this service is `F`, even with a 2048 bit RSA key.

It would make sense to set safe default ciphers, such as those currently suggested by AWS's EC2 load balancer:

    ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:DHE-DSS-AES128-SHA:DES-CBC3-SHA

With these ciphers the quality score goes up to `A`.

**Comment by ianneub** [comment]
:+1: This is what I do on all my proxies.

**Comment by advancingu** [comment]
@tifayuki The ciphers merged above are now capped to grade B.
Using the latest AWS recommendation from 2015-05 with the following settings gets the grade back up to A:
`ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:DES-CBC3-SHA`
