### ISSUE TITLE
Handle multiple backend ports on same host

### ISSUE THREAD

**Issue by jackyphuong** [tutumcloud/haproxy#55]
In case, we have many containers on the same host, such as container 1 run on port 5000, container 2 runs on port 5001,... We cannot configure back end port. Because it assume that all containers run on the same port.

Cheers,

**Comment by tifayuki** [comment]
I have pushed a new version on staging: `tutum/haproxy:staging`. and it should solve the problem.

**Comment by tifayuki** [comment]
https://github.com/tutumcloud/haproxy/commit/70c371a4a4b869c10af5aa4c33c0ea372450bb8a
