### ISSUE TITLE
Password protected sites (htpasswd kind of solution)

### ISSUE THREAD

**Issue by Joostvanderlaan** [tutumcloud/haproxy#56]
We have a couple of Meteor applications running and would like to password protect them. I know I can set the tutum/haproxy to a different port, but from Tutum support I learned there is no way to add something like an htpassword yet. It would be nice to be able to have a specific proxy container (for example for a staging site) with password protection on the site that's behind it.

**Comment by ianneub** [comment]
@Joostvanderlaan I've used this project as well to get a similar effect: https://github.com/bitly/oauth2_proxy

**Comment by tifayuki** [comment]
Introduced envvar `HTTP_BASIC_AUTH` in haproxy container to have limit support of basic auth.
