### ISSUE TITLE
Health check servers under HAproxy

### ISSUE THREAD

**Issue by jackyphuong** [tutumcloud/haproxy#57]
hello,

During create proxy container, how can we configure to HAProxy check web server? Currently, if any server shutdown or crash,.. then we start that container again, HAProxy cannot detect and send request to it. We must restart HAProxy container again.

Cheers,

Jacky

**Comment by tifayuki** [comment]
https://github.com/tutumcloud/haproxy/commit/94c62bfcad72a183b6a08d0a96dd182bcdbc1930
