### ISSUE TITLE
Add RSYSLOG_FORMAT to Configuration

### ISSUE THREAD

**Issue by kytwb** [tutumcloud/haproxy#60]
As mentioned in #43, can't send log to loggly as it as the log format need to include at least a token.
Tried `docker run -it --env RSYSLOG_DESTINATION='logs-01.loggly.com:514?structured_data=df32xxxx-xxxx-xxxx-xxxx-xxxx9cd9c2da@41058' -p 80:80 --link web1:web1 --link web2:web2 tutum/haproxy` but resulted in:

```
[ALERT] 151/052138 (11) : parsing [/etc/haproxy/haproxy.cfg:2] : 'log' : port ranges and offsets are not allowed in 'logs-01.loggly.com:514?structured_data=df32xxxx-xxxx-xxxx-xxxx-xxxx9cd9c2da@41058'
[ALERT] 151/052138 (11) : parsing [/etc/haproxy/haproxy.cfg:3] : 'log' : port ranges and offsets are not allowed in 'logs-01.loggly.com:514?structured_data=df32xxxx-xxxx-xxxx-xxxx-xxxx9cd9c2da@41058'
[ALERT] 151/052138 (11) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
[ALERT] 151/052138 (11) : Fatal errors found in configuration.
```

So proposing a RSYSLOG_FORMAT option.

**Comment by tifayuki** [comment]
@kytwb 
In the recent update, I introduced an new environment variable `EXTRA_GLOBAL_SETTINGS`, where you can add additional lines of settings to the global section of the configuration of haproxy. In you case, I think you can set `-e EXTRA_GLOBAL_SETTINGS='log-format xxxxxxxx'.

Hope it could help.

**Comment by kytwb** [comment]
:+1: I'll try that later on. Thanks for the heads up!

**Comment by kytwb** [comment]
Managed to make it works with `-e RSYSLOG_DESTINATION='logs-01.loggly.com:514'` and `-e EXTRA_DEFAULT_SETTINGS='log-format <14>0\ %t\ %H\ %f\ %pid\ %ID\ [df32xxxx-xxxx-xxxx-xxxx-xxxx9cd9c2da@41058\ tag="haproxy"]\ %Ci:%Cp\ [%t]\ %ft\ %b/%s\ %Tq/%Tw/%Tc/%Tr/%Tt\ %st\ %B\ %cc\ %cs\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ %hr\ %hs\ %{+Q}r\n'`.
Used this [document](www.haproxy.org/download/1.5/doc/configuration.txt) for haproxy log format variables and references.
