### ISSUE TITLE
Stale stack data on stack change in Tutum

### ISSUE THREAD

**Issue by neilellis** [tutumcloud/haproxy#61]
In the example below there is no longer and service called 'server' but you can see it listed under APPZ_VIZZ_BUZZ:

https://www.dropbox.com/s/zuxwksnru5t942d/Screenshot%202015-06-04%2015.58.29.png?dl=0

**Comment by tifayuki** [comment]
I saw you have 2 load balancers, and each of them is still linking to a service named server. It could be a server end problem prevent the definition of haproxy from being updated. Can you open a ticket on tutum, so that we can find where goes wrong. Thank you.
