### ISSUE TITLE
add SESSION_COOKIE documentation

### ISSUE THREAD

**Issue by schmunk42** [tutumcloud/haproxy#62]
> Borja Burgos says:
> June 9, 2015 at 1:05 pm
> Haven’t tried it, but you should be able to enable stickiness with the SESSION_COOKIE env var.

via http://blog.tutum.co/2015/06/08/blue-green-deployment-using-containers/comment-page-1/#comment-12043

Would be nice if this could be documented.

**Comment by tifayuki** [comment]
https://github.com/tutumcloud/haproxy/commit/70c371a4a4b869c10af5aa4c33c0ea372450bb8a
