### ISSUE TITLE
Add compression support

### ISSUE THREAD

**Issue by kytwb** [tutumcloud/haproxy#64]
Thinking of `gzip` here:

```
compression algo gzip
compression type text/html text/plain text/css
```

**Comment by tifayuki** [comment]
`--env GZIP_COMPRESSION_TYPE=text/html text/plain text/css`

**Comment by kytwb** [comment]
Awesome, thanks.

**Comment by Levino** [comment]
Does this work with SSL encryption? I am proxying an amazon bucket with a first haproxy, then encrypting it with a second. Cannot get compression to work.
