### ISSUE TITLE
Virtual host path filters of overlapping scopes cannot be composed

### ISSUE THREAD

**Issue by evq** [tutumcloud/haproxy#68]
Hey,

I really like your container but I couldn't get it to work with my use case without a small change. 
My environment is as follows:

* I have two containers, "web" and "api"
* "api" should get all requests with a path starting with "api" (`VIRTUAL_HOST="*/api, */api/*"`)
* "web" should get all other requests (`VIRTUAL_HOST="*/, */*"`)

No matter which order I linked the "web" and "api" containers to the haproxy container the larger scope (`"*/*"`) was always listed first, thus haproxy always sent requests to the "web" container.

I added a line to sort the list of vhosts in reverse order by length of the path string, which was my hacky way putting things in scope order from smallest to largest. It obviously would break down if the wildcard was in the middle of the path instead.

**Comment by tifayuki** [comment]
Hmm, I think we can add another environment variable like `FRONTEND_PRIORITY`, so that the container with a high priority will always be put before the lower one in the frontend section.

**Comment by tifayuki** [comment]
Added `VIRTUAL_HOST_WEIGHT` to solve this
