### ISSUE TITLE
FORCE_SSL is not redirecting to HTTPS

### ISSUE THREAD

**Issue by advancingu** [tutumcloud/haproxy#71]
In the `latest` release that is currently available on Tutum as of today, `FORCE_SSL` is not redirecting HTTP traffic to HTTPS.

This used to work automatically in `0.1` when a certificate was defined but in `latest` it is not even redirecting with `FORCE_SSL` set to any value.

**Comment by tifayuki** [comment]
What is your stack file?

**Comment by advancingu** [comment]
I use the Tutum GUI and manually added `SSL_BIND_CIPHERS` according to #51 and `SSL_CERT` to provide the certificate. All other environment variables are left at the Tutum default. When testing with `latest` I also added `FORCE_SSL` with `true` or `yes` but both did not have any effect.

**Comment by tifayuki** [comment]
@advancingu Can you open an ticket on Tutum with the service UUID, so that I can check what is wrong?

**Comment by advancingu** [comment]
Sent an email to support.

**Comment by advancingu** [comment]
The issue was that `FORCE_SSL` needs to be set on the application container, not the HAproxy container.
