### ISSUE TITLE
Add support for HSTS

### ISSUE THREAD

**Issue by sam-jay** [tutumcloud/haproxy#72]
Adding the following in haproxy.py right after line 300 if some new env variable is set should do it I think:

frontend.append("rspadd Strict-Transport-Security:\ max-age=31536000;\ includeSubDomains")

**Comment by outrunthewolf** [comment]
Do a pull request if you know where it goes?

**Comment by tifayuki** [comment]
https://github.com/tutumcloud/haproxy/commit/f293ef28c483bf31abb06a442eeacf1c57478e02
