### ISSUE TITLE
Documentation: Failing with 503 error after following tutorial

### ISSUE THREAD

**Issue by keyscores** [tutumcloud/haproxy#74]
Hi there, 
I can't seem to get the HAProxy to work within Tutum. I get a consisten 503 no matter what tutorial I follow. 
Can you please update the tutorial if this image has changed? Tutum is not useful to me if load balancing does not work reliably and easily.

As a suggestion HAproxy should be "baked into" Tutum, much like Rancher is doing. There should be no room for error with load balancing.

**Comment by borjaburgos** [comment]
Can you please provide more information and insight on what exactly you tried please? If you have your setup in a stackfile, sharing that would also help. Thanks.

**Comment by keyscores** [comment]
I'm using the stackfile that you provided to me on our message exchange on tutum.com (intercom). Fails with 503

  lb:
  image: tutum/haproxy
  links:
    - "web:web"
  ports:
    - 80:80
  roles:
    - global
web:
  image: tutum/hello-world
  target_num_containers: 2

**Comment by borjaburgos** [comment]
Can you please provide steps to reproduce? We have run a number of tests and checks and everything is working fine.

**Comment by tifayuki** [comment]
503 error means the container is not reachable from the haproxy container. Usually it is a network issue.
