### ISSUE TITLE
ERROR: Error pulling image (latest) from tutum/haproxy, Untar fork/exec /usr/lib/tutum/docker: cannot allocate memory

### ISSUE THREAD

**Issue by Quexer69** [tutumcloud/haproxy#76]
ERROR: appproxy-1: Error pulling image (latest) from tutum/haproxy, Untar fork/exec /usr/lib/tutum/docker: cannot allocate memory

Occurs till today. Is this a problem with our tutum node?

**Comment by tifayuki** [comment]
As the error message implies there is not enough memory. Probably it is because of the memory leak of docker daemon. You can go to the node monitor section to check if the usage memory is full. If it is the case, you need to restart the docker manually

**Comment by Quexer69** [comment]
yes, the message implies it. I was just wondering because I previously terminated the stack, so there should be no additional memy usage needed. So it must be the memory leak.
I'll try to restart docker manually.

Thanks!
