### ISSUE TITLE
Feature Request for `tune.ssl.cachesize`

### ISSUE THREAD

**Issue by yunspace** [tutumcloud/haproxy#79]
I've been noticing some latency when performing SSL handshakes exceeding 500ms when connecting to Services behind SSL enabled HAProxy. 

Would it be possible to expose the HAProxy `tune.ssl.cachesize` property so that certificates can be cached in order to speed up the handshake process?

**Comment by tifayuki** [comment]
Added `EXTRA_GLOBAL_SETTINGS` in the recent update, which should solve you problem. Pls check it in the README.
