### ISSUE TITLE
Support hdr(host) and hdr_reg(host)

### ISSUE THREAD

**Issue by pilwon** [tutumcloud/haproxy#81]
```
hdr_dom(host) -i domain.com
hdr_dom(host) -i www.domain.com
```

In the above example, the routing rule for `www.domain.com` is blocked by `domain.com`. `VIRTUAL_HOST_WEIGHT` option is quite limited and too much effort for cases where you want to point multiple domains with many subdomains to a single haproxy service as a single entry point to the tutum-created cluster.

It'd be nice to support a syntax where it generates `acl` using `hdr(host)` for exact matching and `hdr_reg` for more advanced pattern matching.

**Comment by pilwon** [comment]
Another big reason we need this feature is a case where you have multiple domains as follows:
* **foo.bar**
* baz**foo.bar**
* qux**foo.bar**
* **foo.bar**.baz

`foo.bar` would match in all of them. It is too easy to route to completely irrelevant backends by mistake if weight is not carefully configured. Adding or removing a domain could cause redeploying entire backends  which is not scalable.

With the latest release of new gTLDs we are exposed to more conflicts like this. For that reason we would need more powerful domain name matching tools rather than limited, error-prone `hdr_dom(host)`.

**Comment by tifayuki** [comment]
@pilwon 
Ideally, if one puts `VIRUTAL_HOST=example.com`, haproxy should match only `example.com` not `www.example.com`(as described in the README). However, `hdr_dom(host)` matches both. This is a bug. 

I'd like to replace all `hdr_dom(host)` to `hdr(host)`, and it should solve the problem.

**Comment by pilwon** [comment]
@tifayuki Thanks, that works! While this solution is perfect for my current requirements, I am curious if there are scenarios where you would actually want `hdr_dom(host)` instead of `hdr(host)`. Looking forward to this update! :+1:

**Comment by tifayuki** [comment]
@pilwon 
Nope, `hdr_dom(example.com)` is equivalent to `hdr_end(.example.com)` or `hdr_reg(.*\.example\.com)`. When writing the code, I didn't think too much on `hdr` and `hdr_dom`, and it turns out I picked up a wrong one :-/

**Comment by tifayuki** [comment]
@pilwon 
After some testing, I found that there are some problems with `hdr(host)`.

If the request url contains port number, the HOST HEADER will also contains the port part. When you use `hdr(host)`, haproxy will not consider it as a correct match.

For example, you set `VIRUAL_HOST=example.com`, then when you do `curl example.com:80`, the HEADER sent by curl is `example.com:80`, and haproxy will give you a 503 error. It even worse when you set a VIRTUAL_HOST using non-standard port. As a result, `hdr_dom(host)` is a cure for this issue.

**Comment by pilwon** [comment]
@tifayuki That's quite interesting. Would it work if we rewrite the host header?

**Comment by tifayuki** [comment]
@pilwon 
I am consider to add another acl rule with the port, so that the config of haproxy looks like

```
frontend port_443
  bind :443 ssl crt /certs/
  reqadd X-Forwarded-Proto:\ https
  acl is_websocket hdr(Upgrade) -i WebSocket
  acl host_rule_1 hdr(host) -i web-b.org
  acl host_rule_1_port hdr(host) -i web-b.org:443
  use_backend SERVICE_WEB_B if host_rule_1 or host_rule_1_port
  acl host_rule_2 hdr(host) -i web-a.org
  acl host_rule_2_port hdr(host) -i web-a.org:443
  use_backend SERVICE_WEB_A if host_rule_2 or host_rule_2_port
```

**Comment by tifayuki** [comment]
fixed: https://github.com/tutumcloud/haproxy/pull/86
