### ISSUE TITLE
EXCLUDE_PORTS not working

### ISSUE THREAD

**Issue by RobQuads** [tutumcloud/haproxy#83]
I have created a container with two ports exposed - 4414 and 7800. When I run the haproxy container as follows the backend service still includes both ports
```
docker run -d --name HAProxy --link Server1:Server1 -e EXCLUDE_PORTS=4414 -p 7800:80 -p 1936:1936 tutum/haproxy
```
The logs from haproxy container includes the following which shows it has two endpoints i.e. the exclude has not worked.
```
backend default_service
  server Server1 172.17.0.42:4414 check
  server Server1 172.17.0.42:7800 check
```
NOTE - The docs are also wrong as they state 
> EXCLUDE_PORTS 8803,8806

where it should be
 > EXCLUDE_PORTS=8803,8806

**Comment by tifayuki** [comment]
hi @RobQuads 

Yes, the README is wrong. Thanks for pointing it out. I have fixed it.

The EXCLUDE_PORTS should be set in the linked services, not in haproxy. Can you try it again?

**Comment by RobQuads** [comment]
Yup that fixed it. The example can probably be made clearer by include a same web app along side the haproxy app. i.e.

docker run -d --name webapp1 -e EXCLUDE_PORTS 8803,8806 mycompany/myimage
docker run -d --link webapp1:webapp1 -p 80:80 tutum/haproxy

My combining the commands in the example its a bit confusing
