### ISSUE TITLE
random requests not passing through?

### ISSUE THREAD

**Issue by johnstontrav** [tutumcloud/haproxy#84]
Hi,

Hard to explain....but every ~5 requests are not passing through to containers.  Instead the haproxy auth prompt shows up.  It goes like this...

1. GET /test/time ---- OK
2. GET /test/time ---- OK
3. GET /test/time ---- OK
4. GET /test/time ---- proxy responds with auth
5. GET /test/time ---- OK
6. GET /test/time ---- OK
7. GET /test/time ---- OK
8. GET /test/time ---- proxy responds with auth

Very strange.

Here is my stack file.

webnode:
  image: 'tutum.co/tjohnston/web-node:v1'
  autoredeploy: true
  deployment_strategy: high_availability
  restart: always
  sequential_deployment: true
  target_num_containers: 3
lb:
  image: 'tutum/haproxy:latest'
  deployment_strategy: high_availability
  links:
    - webnode
  ports:
    - '80:80'
  restart: always
  roles:
    - global
  sequential_deployment: true
  target_num_containers: 2

**Comment by tifayuki** [comment]
Hi,

Can you check if the configuration of haproxy looks good from the log of haproxy container? I mean are there exactly 3 routes in you backend section? make sure that there is no irrelevant routes are added in(usually it happens when you expose more than one port in you application container). 

And also, does it happen when you send request to the service endpoint or container endpoint of haproxy?

**Comment by johnstontrav** [comment]
Hi,

I have check the haproxy logs and the 3 containers are setup correctly.  There is no null routes that i can see.  container endpoints aren't exposing any ports.

Interesting the issue seems to be related to having >1 haproxy.  If i set to 1 I don't get the error.  Scale the haproxy to 2 and after about 8 refreshes it responds with auth.  I can consistantly reproduce this issue.

**Comment by tifayuki** [comment]
I think it has something to do with tutum server side not the haproxy container itself. Can you open a support ticket(with your service UUID, etc) on our website so that we can examine if something goes wrong.
