### ISSUE TITLE
How to redeploy

### ISSUE THREAD

**Issue by lgaticaq** [tutumcloud/haproxy#85]
Start

```bash
docker run -d --name web1 tutum/hello-world
docker run -d --name web2 tutum/hello-world
docker run -d -p 80:80 --link web1:web1 --link web2:web2 tutum/haproxy
```

Redeploy web1

```bash
docker pull tutum/hello-world
docker stop web1
docker rm web1
docker run -d --name web1 tutum/hello-world
sleep 10
docker stop web2
docker rm web2
docker run -d --name web2 tutum/hello-world
```

Also notify to haproxy web1 and web2 online?

**Comment by tifayuki** [comment]
If you run haproxy with Tutum, when the applications are redeployed, haproxy will automatically reload when web1 and web2 are online.

If you run haproxy out of Tutum, you have to terminate the current haproxy container and create a new one.

**Comment by lgaticaq** [comment]
thanks
