### ISSUE TITLE
Port number in virtual domain routing with regular expression

### ISSUE THREAD

**Issue by valentin69** [tutumcloud/haproxy#88]
Using both virtual domain routing, a regex in the VIRTUAL_HOST and a port number other than 80, the port number is currently overlooked in that case on the generated hdr_reg acl config line.
Thus, production an inconsistent behaviour between fixed (VIRTUAL_HOST=www.my.domain.com:8080), and regex domains (VIRTUAL_HOST=www.*.domain.com:8080).

**Comment by tifayuki** [comment]
Hi @valentin69 

Can you tell us more detailed info on the inconsistence?

**Comment by valentin69** [comment]
Hello @tifayuki 
The inconsistence is that :
with VIRTUAL_HOST=www.my.domain.com:8080 the generated acl line has the port number ;
while for VIRTUAL_HOST=www.*.domain.com:8080 the generated acl line ignores the port number.

**Comment by tifayuki** [comment]
True

I have pushed a fix, which adds another rule with port no matter if there is wildcard or not

Thank you for reporting this :)

**Comment by valentin69** [comment]
Thanks. My pleasure to help such a great team.
