### ISSUE TITLE
Enable ProxyProtocol support

### ISSUE THREAD

**Issue by yunspace** [tutumcloud/haproxy#90]
In order to setup proxy protocol behind AWS ELB similar to https://github.com/jvehent/haproxy-aws, `accept-proxy` needs to be enabled during `ssl bind`.

Using `SSL_BIND_OPTIONS` environment variable doesn't seem to work because it adds the options to the global parameters. 

I believe the change needs to be made in https://github.com/tutumcloud/haproxy/blob/master/haproxy/haproxy.py#L389 but needs to be made configurable

**Comment by tifayuki** [comment]
https://github.com/tutumcloud/haproxy/commit/4a01ce3bd724a6166a82be1d877564cbc61e57d3
