### ISSUE TITLE
Loadbalancer routes crazy when stack service is being redeployed

### ISSUE THREAD

**Issue by Levino** [tutumcloud/haproxy#95]
We have this service running as a load balancer for a stack (and 5 microservices, each running on port 3000). If I redeploy one service, often the loadbalancers goes into "crazy mode" just randomly resolving queries to hostnames with different backend services. Something about the hostname resolution gets messed up. Only a load balancer redeploy helps. This is VERY annoying.

**Comment by tifayuki** [comment]
Hi Levino,

I never saw this error before. There is no name resolution in haproxy container. The configuration is generation from the result of API calls of Tutum.I am guessing something goes wrong in the API call. 

Can you open a support ticket on tutum, so that we can check it case by case.
(with you service uuid, and also the log if possible)

Thank you.

**Comment by Levino** [comment]
@tifayuki Sure can do.

**Comment by Levino** [comment]
Found out the issue: It happens when a service stops (haproxy will be restarted through the API) and then is started again (no restart for haproxy on service restart!!!)

**Comment by devpascoe** [comment]
same, i was getting a completely different website...in Italian

**Comment by Levino** [comment]
This sounds like something different. Rather at dns level. I was getting other services that I am running myself behind the same loadbalancer but under different hostnames. My issue has been resolved. It was a blocking refresh of the ha proxy config on service redeploy. As there is a running websocket service through the loadbalancer it was waiting for it to finish (around five minutes) and only then reloading the new config. Until then it would not take any new "refresh" commands through the api but drop them and then go into an onconfigured state or so. Latest images fixes it.
